package superapp.miniapps.commands;

public enum CommandsEnum {

	CREATE_RECIPE,
	MODIFY_RECIPE,
	DELETE_RECIPE,
	DELETE_ALL_RECIPES,
	FIND_RECIPE,
	GET_ALL_RECIPES,
	FOLLOW_DIETITIAN,
	UNFOLLOW_DIETITIAN,
	ADD_INGREDIENT,
	REMOVE_INGREDIENT,
	GET_RANDOM_RECIPE
}
